version: "3.9"

services:
  api:
    build: ./api
    container_name: demand_api
    ports:
      - "8000:8000"
    volumes:
      - ./api/models:/app/api/models

  dashboard:
    build: ./dashboards
    container_name: demand_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    volumes:
      - ./dashboards/models:/app/models
